development:
  adapter: postgresql
  encoding: unicode
  database: r2013-04-03-tiny-dancer_development
  pool: 5
  host: localhost
  username: chyld
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: r2013-04-03-tiny-dancer_test
  pool: 5
  host: localhost
  username: chyld
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: r2013-04-03-tiny-dancer_production
  pool: 5
  host: localhost
  username: chyld
  password:
