development:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-21-hacker-news_development
  pool: 5
  host: localhost
  username: chyld
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-21-hacker-news_test
  pool: 5
  host: localhost
  username: chyld
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-21-hacker-news_production
  pool: 5
  host: localhost
  username: chyld
  password:
